# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yan Ting Yuen
email: yantingyuen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yantingyuen.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yantingyuen
facebook_username: yanting.yuen
imdb_url:
copyright: 2017 Yan Ting Yuen
copyright_chinese: 袁欣婷

bg-url: /img/bg_alt.svg

# Default settings
defaults:
  - scope:
      path: ""
      type: work
    values:
      author: Yan Ting
      layout: work-title
      title: ""
      img-name: ""
      img-alt: ""
      vimeo: https://player.vimeo.com/video/
      copyright_country_year: Yan Ting Yuen (2017), Netherlands
  -
    scope:
      path: ""
      type: news
    values:
      layout: news
      title: ""
      title-chinese:
      img-name: ""
      img-alt: ""
      author: Yan Ting
      excerpt: ""

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

collections:
  work:
    output: true
    permalink: /:path/
  news:
    output: true
    permalink: /:path/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
